package com.doomscroll.client;

import com.google.gson.JsonObject;
import com.google.gson.JsonParser;

import com.mojang.blaze3d.systems.RenderSystem;
import com.mojang.blaze3d.textures.AddressMode;
import com.mojang.blaze3d.textures.FilterMode;
import com.mojang.blaze3d.textures.GpuSampler;
import com.doomscroll.cef.api.CefService;
import com.doomscroll.cef.api.CefBrowserView;
import net.minecraft.core.BlockPos;
import net.minecraft.world.phys.Vec3;
import org.jetbrains.annotations.Nullable;

import java.util.OptionalDouble;

/**
 * Single global browser (MVP): all screens show the same browser.
 */
public final class Browsers {
	public static final String URL_SHORTS = "https://www.youtube.com/shorts";
	public static final String URL_REELS = "https://www.instagram.com/reels/";
	public static final String URL_TIKTOK = "https://www.tiktok.com/";
	/** Home menus: screen (doomscroll://home/screen) and tablet (doomscroll://home/tablet); generated by HomePages. */
	public static final String HOME_URL = HomePages.SCREEN;
	public static final String TABLET_HOME_URL = HomePages.TABLET;
	public static final String URL_YT_LOGIN = "https://accounts.google.com/ServiceLogin?service=youtube&continue=https://www.youtube.com/";

	/** Start page of a screen browser: that screen's home menu (the queue list belongs to the screen). */
	public static String homeUrlFor(@Nullable BlockPos anchor) {
		return HomePages.screenUrl(anchor);
	}

	/** Sync: the screen address received from the server before the browser exists; the browser opens straight on it (avoids a race with the home page). */
	private static String initialScreenUrl = "";
	public static void setInitialScreenUrl(String url) { initialScreenUrl = url == null ? "" : url; }

	/** Screen browser resolution (config/doomscroll.json). */
	public static int screenWidth() { return DoomscrollConfig.get().screenWidth; }
	public static int screenHeight() { return DoomscrollConfig.get().screenHeight; }

	/** When the setting changes, resizes the running browser immediately and saves. */
	public static void applyScreenResolution() {
		DoomscrollConfig.save();
		ScreenBrowsers.resizeAll();
		ScreenBrowsers.refreshQuality(); // the YouTube quality cap derives from the resolution
	}

	private static final double FADE_START = 6.0;
	private static final double FADE_END = 30.0;

	@Nullable
	private static CefBrowserView browser;
	@Nullable
	private static GpuSampler sampler;
	@Nullable
	private static Vec3 lastScreenPos;
	private static float lastAppliedVolume = -1f;


	private Browsers() {}

	private static long lastInitNoticeNanos = 0L;

	@Nullable
	public static CefBrowserView getOrCreate() {
		return ScreenBrowsers.activeBrowser(); // screen browsers are opened by the renderer; this returns the active one
	}

	// ---- tablet: a second browser, independent of the screen ----

	/** Landscape: WD pad surface ratio (27.65:14 ~ 1.98). Portrait (phone): 9:16. */
	private static boolean tabletPortrait = false;
	public static boolean isTabletPortrait() { return tabletPortrait; }
	public static int tabletWidth() { return tabletPortrait ? 720 : 1280; }
	public static int tabletHeight() { return tabletPortrait ? 1280 : 644; }

	/** R key: portrait/landscape. If the browser exists it is resized immediately. */
	public static void setTabletPortrait(boolean portrait) {
		tabletPortrait = portrait;
		if (tablet != null) {
			tablet.resize(tabletWidth(), tabletHeight());
		}
	}
	@Nullable
	private static CefBrowserView tablet;

	@Nullable
	public static CefBrowserView getOrCreateTablet() {
		if (tablet == null) {
			var init = CefService.initialize();
			if (!init.isDone()) {
				return null;
			}
			try {
				// The tablet is yours: persistent profile (so your logins stay).
				tablet = init.getFuture().join().createBrowser(TABLET_HOME_URL, false, false);
				tablet.resize(tabletWidth(), tabletHeight());
				final CefBrowserView tb = tablet;
				tb.setMessageListener(msg -> net.minecraft.client.Minecraft.getInstance().execute(() -> {
					if (tablet != tb) {
						return;
					}
					if (msg.contains("fsArmed") || msg.contains("\"cinema\"")) {
						try {
							if (cinemaMessage(tb, tabletCinema, com.google.gson.JsonParser.parseString(msg).getAsJsonObject())) {
								return;
							}
						} catch (Exception ignored) {
							// not JSON: fall through
						}
					}
					if (msg.contains("\"popup\"")) {
						tabletLastPopup = popupUrl(msg);
						popupNotice(tabletLastPopup);
						return;
					}
					onTabletMessage(msg);
				}));
			} catch (Exception e) {
				com.doomscroll.Doomscroll.LOGGER.error("could not create the tablet browser", e);
				return null;
			}
		}
		return tablet;
	}

	/** Last blocked popup address in the tablet browser (opened with /ds popup). */
	public static String tabletLastPopup = "";
	private static long lastPopupNoticeMs = 0L;

	static String popupUrl(String msg) {
		try {
			return com.google.gson.JsonParser.parseString(msg).getAsJsonObject().get("popup").getAsString();
		} catch (Exception e) {
			return "";
		}
	}

	/** Blocked-popup notice (at most one per 10 s). */
	static void popupNotice(String url) {
		long now = System.currentTimeMillis();
		if (url.isEmpty() || now - lastPopupNoticeMs < 10_000L) {
			return;
		}
		lastPopupNoticeMs = now;
		var mc = net.minecraft.client.Minecraft.getInstance();
		if (mc.player != null) {
			String host = url.replaceFirst("^https?://", "").replaceFirst("/.*$", "");
			mc.player.sendOverlayMessage(net.minecraft.network.chat.Component.translatable("message.doomscroll.popup_blocked", host));
		}
	}

	@Nullable
	public static CefBrowserView getTabletIfPresent() {
		return tablet;
	}

	public static void closeTablet() {
		if (tablet != null) {
			try {
				tabletJs("document.querySelectorAll('video,audio').forEach(function(m){ m.pause(); m.src = ''; });");
				tablet.getCefBrowser().stopLoad();
				tablet.getCefBrowser().loadURL("about:blank");
			} catch (Exception ignored) {
			}
			try {
				tablet.close();
			} catch (Exception ignored) {
			}
			tablet = null;
		}
		// When the server changes and we return to the same address, avoid landing in the "already reported" state.
		tabletReportUrl = "";
	}

	/**
	 * Sound stops when the tablet goes into the pocket and resumes when it comes out. The page's own volume setting
	 * (YouTube slider, mute button) is left alone: the tablet is personal, a volume the user turned down on the page should stay down.
	 */
	public static void tabletVisible(boolean visible) {
		if (tablet == null) {
			return;
		}
		tablet.setFrameRate(visible ? DoomscrollConfig.get().browserFps : 8);
		if (visible) {
			tabletJs("document.querySelectorAll('video,audio').forEach(function(m){ if (m.paused) { m.play().catch(function(){}); } });");
		} else if (!Broadcast.testTabletViewer) { // in the smoke test the tablet is the broadcast receiver: do not pause
			tabletJs("document.querySelectorAll('video,audio').forEach(function(m){ m.pause(); });");
		}
	}

	public static void tabletNavigate(String input) {
		String url = input.trim();
		if (url.isEmpty()) {
			return;
		}
		CefBrowserView b = getOrCreateTablet();
		if (b == null) {
			return;
		}
		if (!url.contains("://")) {
			url = url.contains(".") && !url.contains(" ") ? "https://" + url : searchUrl(url);
		}
		b.getCefBrowser().loadURL(url);
	}

	public static void goBackTablet() {
		CefBrowserView b = tablet;
		if (b != null && b.getCefBrowser().canGoBack()) {
			b.getCefBrowser().goBack();
		}
	}

	public static void goForwardTablet() {
		CefBrowserView b = tablet;
		if (b != null && b.getCefBrowser().canGoForward()) {
			b.getCefBrowser().goForward();
		}
	}

	public static void reloadTablet() {
		CefBrowserView b = tablet;
		if (b != null) {
			b.getCefBrowser().reload();
		}
	}

	private static String tabletReportUrl = "";
	private static double tabletTime = -1;
	private static double tabletDuration = 0;
	private static boolean tabletPaused = true;
	private static long tabletTimeStampMs = 0L;

	/** Position of the video on the tablet (s), -1 when there is no report. */
	public static double tabletTime() {
		return tabletTime;
	}

	public static double tabletDuration() { return tabletDuration; }
	public static boolean tabletPaused() { return tabletPaused; }

	/** Position corrected by the time elapsed since the last report; -1 when the report is stale. */
	public static double tabletNow() {
		if (tabletDuration <= 0 || tabletTime < 0 || System.currentTimeMillis() - tabletTimeStampMs > 3000L) {
			return -1;
		}
		return tabletPaused ? tabletTime : tabletTime + (System.currentTimeMillis() - tabletTimeStampMs) / 1000.0;
	}
	private static String tabletTitle = "";
	/** Tablet page report (time/address/title). Subtitle and focus messages are not used on the tablet. */
	private static void onTabletMessage(String json) {
		try {
			JsonObject o = JsonParser.parseString(json).getAsJsonObject();
			if (o.has("home")) {
				HomePages.onTabletCommand(o); // home menu command (remove bookmark, clear history)
				return;
			}
			if (o.has("bcinfo")) {
				Broadcast.onTabletReady();
				return;
			}
			if (o.has("bct")) {
				tabletTime = o.get("bct").getAsDouble();
				return;
			}
			if (!o.has("t")) {
				return;
			}
			tabletTime = o.get("t").getAsDouble();
			tabletDuration = o.has("d") ? o.get("d").getAsDouble() : 0;
			tabletPaused = o.has("p") && o.get("p").getAsInt() == 1;
			tabletTimeStampMs = System.currentTimeMillis();
			if (o.has("ti")) {
				tabletTitle = o.get("ti").getAsString();
			}
			String u = o.has("u") ? o.get("u").getAsString() : "";
			if (!u.equals(tabletReportUrl)) {
				tabletReportUrl = u;
				TabletBookmarks.noteVisit(u, tabletTitle()); // history
			} else if (o.has("ti")) {
				TabletBookmarks.updateTitle(u, tabletTitle()); // the title arrived later (SPA)
			}
			if (o.has("ti") && !tabletTitle().isBlank()) {
				PageTitles.remember(u, tabletTitle());
			}
		} catch (Exception ignored) {
		}
	}

	/** Title of the page on the tablet (with the " - YouTube" suffix stripped) or "". */
	public static String tabletTitle() {
		String t = tabletTitle == null ? "" : tabletTitle.trim();
		int dash = t.lastIndexOf(" - ");
		return dash > 8 ? t.substring(0, dash) : t;
	}

	public static String tabletUrl() {
		CefBrowserView b = tablet;
		if (b == null) {
			return "";
		}
		String u = b.getCefBrowser().getURL();
		return u == null ? "" : u;
	}

	private static void tabletJs(String code) {
		CefBrowserView b = tablet;
		if (b != null) {
			b.getCefBrowser().executeJavaScript(code, b.getCefBrowser().getURL(), 0);
		}
	}

	public static boolean isIdlePaused() { return !ScreenBrowsers.activeOn(); }
	@Nullable public static Vec3 lastScreenPos() { return ScreenBrowsers.activeCenter(); }

	/** Is this a vertical short-form video page like Shorts / Reels / TikTok? (wheel -> arrow key, auto-advance) */
	public static boolean isShortFormPage(String url) {
		if (url == null) return false;
		String u = url.toLowerCase();
		return u.contains("youtube.com/shorts") || u.contains("instagram.com/reels") || u.contains("instagram.com/reel/") || u.contains("tiktok.com");
	}

	/**
	 * Installs an idempotent watcher on the page: when the video ends or rewinds to the start (Shorts loop) it writes
	 * "__DS_NEXT__" to the console; mcef-codec catches that and sends the page a reliable ArrowDown key.
	 */
	/**
	 * In-page navigation: clicks the site's own next/previous button (YouTube Shorts, TikTok, Instagram),
	 * falls back to a keyboard event when there is no button. Far more reliable than pressing keys in the browser.
	 */
	private static final String NAV_JS =
			"if(!window.__dsNext){"
			+ "window.__dsClick=function(sel){var b=document.querySelector(sel);if(b){b.click();return true;}return false;};"
			+ "window.__dsKey=function(k,c){var ev=new KeyboardEvent('keydown',{key:k,code:k,keyCode:c,which:c,bubbles:true,cancelable:true});"
			+ "(document.activeElement||document.body).dispatchEvent(ev);document.dispatchEvent(ev);};"
			+ "window.__dsScrollable=function(el){while(el&&el!==document.body){var st=getComputedStyle(el);if(/(auto|scroll)/.test(st.overflowY)&&el.scrollHeight>el.clientHeight+10)return el;el=el.parentElement;}return document.scrollingElement||document.documentElement;};"
			+ "window.__dsScrollVideo=function(dir){var v=document.querySelector('video');var c=window.__dsScrollable(v);var h=v?Math.max(200,v.getBoundingClientRect().height):c.clientHeight;c.scrollBy({top:dir*h,left:0,behavior:'smooth'});};"
			+ "window.__dsNext=function(){if(location.hostname.indexOf('instagram.com')>=0){window.__dsScrollVideo(1);return;}if(window.__dsClick('#navigation-button-down button, button[aria-label=\"Next video\"], [data-e2e=\"arrow-right\"], button[aria-label=\"Next\"]'))return;window.__dsKey('ArrowDown',40);};"
			+ "window.__dsPrev=function(){if(location.hostname.indexOf('instagram.com')>=0){window.__dsScrollVideo(-1);return;}if(window.__dsClick('#navigation-button-up button, button[aria-label=\"Previous video\"], [data-e2e=\"arrow-left\"], button[aria-label=\"Previous\"]'))return;window.__dsKey('ArrowUp',38);};"
			+ "}";

	private static final String AUTO_NEXT_JS = NAV_JS +
			"(function(){if(window.__dsAuto)return;window.__dsAuto=true;window.__dsLastNext=0;"
			+ "function next(){var t=Date.now();if(t-window.__dsLastNext<2000)return;window.__dsLastNext=t;console.log('__DS_NEXT__');window.__dsNext();}"
			+ "setInterval(function(){document.querySelectorAll('video').forEach(function(v){if(v.__ds)return;v.__ds={last:0,src:v.currentSrc};"
			+ "v.addEventListener('timeupdate',function(){"
			+ "if(v.currentSrc!==v.__ds.src){v.__ds.src=v.currentSrc;v.__ds.last=0;return;}"
			+ "var d=v.duration;if(d>1&&v.__ds.last>d-0.7&&v.currentTime<0.5&&!v.paused){v.__ds.last=0;next();}else{v.__ds.last=v.currentTime;}});"
			+ "v.addEventListener('ended',next);});},1000);})();";

	/**
	 * Cinema mode, off. Runs in every frame (jsAllFrames): the frame that owns fullscreen leaves it, a CSS-pinned
	 * player gets its styles back. Only the top frame reports: {"cinema":"off"} when something was undone,
	 * {"cinema":"noop"} when nothing was on (Java then turns cinema on instead, so a stale flag never eats a press).
	 */
	private static final String CINEMA_OFF_JS =
			"(function(){var TOP;try{TOP=(window===window.top);}catch(e){TOP=false;}var done=false;window.__dsCinBusy=0;"
			+ "var ov=document.getElementById('__dsFsOv');if(ov)ov.remove();"
			+ "if(window.__dsCinema){var c=window.__dsCinema;try{if(c.pop){try{c.el.hidePopover();}catch(e){}c.el.removeAttribute('popover');}c.el.style.cssText=c.css;document.documentElement.style.overflow=c.ov;document.body.style.overflow=c.bov;if(c.inner)c.inner.style.cssText=c.innerCss;}catch(e){}window.__dsCinema=null;done=true;}"
			+ "if(document.fullscreenElement){try{var p=document.exitFullscreen();if(p&&p.catch)p.catch(function(){});}catch(e){}done=true;}"
			+ "if(TOP)console.log('__DS__{\"cinema\":\"'+(done?'off':'noop')+'\"}');})();";

	/**
	 * Top-frame side of the cinema hand-shake, installed with the page reporter so it is in place before any
	 * sub-frame speaks (frames run the cinema script in no particular order). "claim": a sub-frame has a video and
	 * takes the job. "armed": that frame waits for the click; answer with the centre of the iframe that contains it.
	 * "fallback": fullscreen was refused inside; handle the iframe from up here.
	 * It also reports every fullscreen change of the page, including the site's own fullscreen button, so the next
	 * Cinema press knows it has to turn fullscreen off.
	 */
	private static final String CINEMA_MSG_JS =
			"(function(){var TOP;try{TOP=(window===window.top);}catch(e){TOP=false;}if(!TOP||window.__dsCinMsg)return;"
			+ "window.__dsCinMsg=1;window.__dsCinClaim=0;window.__dsCinFb=0;"
			+ "document.addEventListener('fullscreenchange',function(){console.log('__DS__{\"cinema\":\"'+(document.fullscreenElement?'on':'off')+'\"}');});"
			+ "window.addEventListener('message',function(ev){var d=ev.data;if(!d||typeof d!=='object'||!d.__dsCin)return;"
			+ "if(d.__dsCin==='claim'){window.__dsCinClaim=Date.now();return;}"
			+ "var w=ev.source,f=null;try{var g=0;while(w&&w.parent!==window&&g++<16)w=w.parent;}catch(e){}"
			+ "var ifr=document.querySelectorAll('iframe');for(var i=0;i<ifr.length;i++){try{if(ifr[i].contentWindow===w){f=ifr[i];break;}}catch(e){}}"
			+ "if(d.__dsCin==='armed'){if(f){var r=f.getBoundingClientRect();console.log('__DS__{\"fsArmed\":1,\"x\":'+Math.round(r.left+r.width/2)+',\"y\":'+Math.round(r.top+r.height/2)+'}');}else{console.log('__DS__{\"fsArmed\":1}');}}"
			+ "else if(d.__dsCin==='fallback'&&f&&Date.now()-window.__dsCinFb>3000){window.__dsCinFb=Date.now();if(window.__dsCinemaRun)window.__dsCinemaRun(f);}});})();";

	/**
	 * Cinema mode, on. Runs in every frame (jsAllFrames). The Fullscreen API needs a user gesture, so the frame that
	 * takes the job puts a one-shot transparent cover on the page and Java clicks it (see {@link #armedClick}); the
	 * cover's handler presses the site's own fullscreen button when there is one, otherwise calls requestFullscreen
	 * on the player container. A sub-frame that holds the video claims the job (postMessage to top) and the top
	 * frame answers with the click point (centre of that iframe); the top frame handles iframes itself only when no
	 * sub-frame claimed within 300 ms. When fullscreen is refused, the top frame pins the player itself: fixed to the
	 * viewport and promoted to the top layer as a manual popover, so no site header, transformed ancestor or
	 * z-index can cover it (plain z-index lost to site headers). Only the top frame reports:
	 * {"cinema":"on"|"off"|"none"}, "none" meaning no player was found on the page.
	 */
	private static final String CINEMA_ON_JS = CINEMA_MSG_JS
			+ "(function(){var TOP;try{TOP=(window===window.top);}catch(e){TOP=false;}"
			+ "var rep=function(k){if(TOP)console.log('__DS__{\"cinema\":\"'+k+'\"}');};"
			+ "var post=function(k){try{window.top.postMessage({__dsCin:k},'*');}catch(e){}};"
			+ "if(window.__dsCinema||document.fullscreenElement){rep('on');return;}"
			+ "var VW=innerWidth,VH=innerHeight,VA=Math.max(1,VW*VH);"
			+ "function score(e){var r=e.getBoundingClientRect();var A=r.width*r.height;if(A<40000||r.width<160)return -99;var sc=0;"
			+ "if(TOP&&A>0.93*VA)sc-=3;var ar=r.width/Math.max(1,r.height);if(ar>1.2&&ar<2.5)sc+=1;"
			+ "var cx=r.left+r.width/2,cy=r.top+r.height/2;if(Math.abs(cx-VW/2)<VW*0.25&&Math.abs(cy-VH/2)<VH*0.35)sc+=1;"
			+ "var st=getComputedStyle(e);if(st.pointerEvents==='none'||st.visibility==='hidden'||st.opacity==='0')sc-=3;"
			+ "if(e.tagName==='VIDEO'){if(!e.paused&&e.currentTime>0)sc+=3;if(e.duration>60)sc+=1;if(e.loop&&e.muted)sc-=3;if(!e.src&&!e.currentSrc&&!e.querySelector('source'))sc-=2;}"
			+ "else{var src=(e.src||'').toLowerCase();if(/player|embed|video|stream|play|vid|sibnet|ok[.]ru|dailymotion|vk[.]com/.test(src))sc+=2;if(/bet|casino|(^|[^a-z])ads?([^a-z]|$)|adserv|banner|promo|sponsor|track|pixel|analytics|doubleclick|recaptcha|hcaptcha/.test(src))sc-=5;if(!src)sc-=1;}"
			+ "return sc+Math.min(2,A/VA*2);}"
			+ "var FSBTN='.ytp-fullscreen-button,.vjs-fullscreen-control,.jw-icon-fullscreen,[data-plyr=\"fullscreen\"],.dplayer-full-icon,.art-control-fullscreen,.fp-fullscreen,.fullscreen-button,.btn-fullscreen,[aria-label=\"Full screen\"],[aria-label=\"Fullscreen\"],[aria-label=\"Tam ekran\"],[title=\"Full screen\"],[title=\"Fullscreen\"],[title=\"Tam ekran\"]';"
			+ "function run(el){if(window.__dsCinBusy&&Date.now()-window.__dsCinBusy<3000)return;window.__dsCinBusy=Date.now();"
			+ "var r=el.getBoundingClientRect();var p=el;while(p.parentElement&&p.parentElement!==document.body){var pr=p.parentElement.getBoundingClientRect();if(pr.width*pr.height>r.width*r.height*1.35)break;p=p.parentElement;}"
			+ "var pin=function(){if(window.__dsCinema||document.fullscreenElement)return;"
			+ "var c={el:p,css:p.style.cssText,ov:document.documentElement.style.overflow,bov:document.body.style.overflow,inner:el!==p?el:null,innerCss:el!==p?el.style.cssText:'',pop:false};window.__dsCinema=c;"
			+ "p.style.cssText+=';position:fixed!important;top:0!important;left:0!important;right:0!important;bottom:0!important;width:100vw!important;height:100vh!important;max-width:none!important;max-height:none!important;margin:0!important;padding:0!important;border:0!important;overflow:hidden!important;z-index:2147483647!important;background:#000!important;';"
			+ "try{if(p.showPopover&&!p.hasAttribute('popover')){p.setAttribute('popover','manual');p.showPopover();c.pop=true;}}catch(e){try{p.removeAttribute('popover');}catch(e2){}}"
			+ "if(el!==p){el.style.width='100%';el.style.height='100%';el.style.objectFit='contain';}"
			+ "document.documentElement.style.overflow='hidden';document.body.style.overflow='hidden';rep('on');};"
			+ "var fail=function(){window.__dsCinBusy=0;if(TOP)pin();else post('fallback');};"
			+ "var fs=p.requestFullscreen||p.webkitRequestFullscreen;if(!fs||!document.fullscreenEnabled){fail();return;}"
			+ "var old=document.getElementById('__dsFsOv');if(old)old.remove();"
			+ "var ov=document.createElement('div');ov.id='__dsFsOv';ov.style.cssText='position:fixed;left:0;top:0;z-index:2147483647;background:transparent;'+(TOP?'width:12px;height:12px;':'width:100vw;height:100vh;');"
			+ "var fired=false;var go=function(ev){if(fired)return;fired=true;ev.stopPropagation();ev.preventDefault();ov.remove();"
			+ "var btn=null;try{var b=p.querySelector(FSBTN)||(el.parentElement?el.parentElement.querySelector(FSBTN):null);if(b&&b.offsetWidth)btn=b;}catch(e){}"
			+ "try{if(btn){btn.click();}else{var pr=fs.call(p,{navigationUI:'hide'});if(pr&&pr.catch)pr.catch(function(){fail();});}}catch(e){fail();}"
			+ "setTimeout(function(){if(!document.fullscreenElement)fail();},1500);};"
			+ "ov.addEventListener('mousedown',function(ev){ev.stopPropagation();ev.preventDefault();});"
			+ "ov.addEventListener('mouseup',go);ov.addEventListener('click',go);"
			+ "document.documentElement.appendChild(ov);"
			+ "setTimeout(function(){if(document.getElementById('__dsFsOv')===ov){ov.remove();if(!fired){fired=true;fail();}}},2500);"
			+ "if(TOP)console.log('__DS__{\"fsArmed\":1}');else post('armed');}"
			+ "window.__dsCinemaRun=function(f){if(f)run(f);};"
			+ "var cands=[].slice.call(document.querySelectorAll(TOP?'video,iframe':'video')).map(function(e){return {e:e,s:score(e)};}).filter(function(c){return c.s>-5;}).sort(function(a,b){return b.s-a.s;});"
			+ "var best=cands.length?cands[0].e:null;"
			+ "if(!TOP){if(best){post('claim');setTimeout(function(){post('claim');},150);run(best);}return;}"
			+ "if(!best){setTimeout(function(){if(Date.now()-window.__dsCinClaim>400)rep('none');},350);return;}"
			+ "if(best.tagName==='VIDEO'){run(best);return;}"
			+ "setTimeout(function(){if(Date.now()-window.__dsCinClaim>400)run(best);},300);"
			+ "})();";

	/** Cinema state of one browser (a screen or the tablet); kept in sync by the page's reports. */
	public static final class Cinema {
		public boolean on = false;
		long offSentMs = 0L;
	}

	private static final Cinema tabletCinema = new Cinema();

	/** Remote / command / tablet button: off if the page says it is on, otherwise on. */
	public static void cinemaToggle(@Nullable CefBrowserView b, Cinema st) {
		if (b == null) {
			return;
		}
		if (st.on) {
			st.offSentMs = System.currentTimeMillis();
			jsAllFrames(b, CINEMA_OFF_JS);
		} else {
			jsAllFrames(b, CINEMA_ON_JS);
		}
	}

	/** Page message about cinema / fullscreen; true when it was one. Game thread. */
	public static boolean cinemaMessage(@Nullable CefBrowserView b, Cinema st, com.google.gson.JsonObject o) {
		if (o.has("fsArmed")) {
			armedClick(b, o.has("x") ? o.get("x").getAsInt() : 6, o.has("y") ? o.get("y").getAsInt() : 6);
			return true;
		}
		if (!o.has("cinema")) {
			return false;
		}
		switch (o.get("cinema").getAsString()) {
			case "on" -> st.on = true;
			case "off" -> st.on = false;
			case "noop" -> {
				st.on = false;
				if (b != null && System.currentTimeMillis() - st.offSentMs < 2000L) {
					st.offSentMs = 0L;
					jsAllFrames(b, CINEMA_ON_JS); // the flag was stale: the press meant "on"
				}
			}
			case "none" -> notice("message.doomscroll.cinema.none");
			default -> { }
		}
		return true;
	}

	static void notice(String key) {
		var mc = net.minecraft.client.Minecraft.getInstance();
		if (mc.player != null) {
			mc.player.sendOverlayMessage(net.minecraft.network.chat.Component.translatable(key));
		}
	}

	/** The page waits for a user gesture: click its one-shot cover (top-left corner, or the centre of the claiming iframe). */
	public static void armedClick(@Nullable CefBrowserView b, int x, int y) {
		if (b == null) {
			return;
		}
		x = Math.max(0, x);
		y = Math.max(0, y);
		var info = new net.minecraft.client.input.MouseButtonInfo(org.lwjgl.glfw.GLFW.GLFW_MOUSE_BUTTON_LEFT, 0);
		b.onMouseMoved(x, y);
		b.onMouseClicked(new net.minecraft.client.input.MouseButtonEvent(x, y, info), false);
		b.onMouseReleased(new net.minecraft.client.input.MouseButtonEvent(x, y, info));
	}

	/**
	 * Page reporter: once a second reports the position of the largest/playing video to Java over the console
	 * (__DS__ channel). Also the viewer alignment helpers (__dsSeek, __dsSetPaused). Idempotent.
	 */
	private static final String REPORT_JS =
			"if(!window.__dsRep){window.__dsRep=1;window.__dsFr=Math.floor(Math.random()*1e9);"
			+ "window.__dsVid=function(){var best=null,bs=-1;[].slice.call(document.querySelectorAll('video')).forEach(function(v){if(!(v.duration>0))return;var r=v.getBoundingClientRect();var sc=r.width*r.height+(v.paused?0:1e7);if(sc>bs){bs=sc;best=v;}});return best;};"
			+ "window.__dsSeek=function(t){var v=window.__dsVid();if(v){try{v.currentTime=t;}catch(e){}}};"
			+ "window.__dsSetPaused=function(p){var v=window.__dsVid();if(!v)return;if(p){v.pause();}else{v.play().catch(function(){});}};"
			+ "setInterval(function(){"
			+ "if(window.__dsAdSkip!==false&&window.__dsAdClean)window.__dsAdClean();"
			+ "if(window.__dsFocusSend)window.__dsFocusSend();"
			+ "var v=window.__dsVid();if(!v)return;var d=v.duration;if(!v.__dsEnd){v.__dsEnd=1;v.addEventListener('ended',function(){var ad=document.querySelector('.html5-video-player.ad-showing')?1:0;console.log('__DS__{\"ended\":1,\"fr\":'+window.__dsFr+',\"d\":'+Math.round(v.duration||0)+',\"ad\":'+ad+'}');});}"
			+ "console.log('__DS__'+JSON.stringify({t:Math.round(v.currentTime*10)/10,d:isFinite(d)?Math.round(d*10)/10:0,p:v.paused?1:0,u:location.href,fr:window.__dsFr,ti:(document.title||'').slice(0,100)}));},1000);"
			+ "window.__dsFsFix=function(f){if(!f||f.dataset.dsFs)return;f.dataset.dsFs='1';if(!f.hasAttribute('allowfullscreen'))f.setAttribute('allowfullscreen','');var a=f.getAttribute('allow')||'';if(!/fullscreen/.test(a))f.setAttribute('allow',(a?a+'; ':'')+'fullscreen');};"
			+ "[].slice.call(document.querySelectorAll('iframe')).forEach(window.__dsFsFix);"
			+ "try{new MutationObserver(function(ms){ms.forEach(function(m){[].slice.call(m.addedNodes).forEach(function(n){if(n.tagName==='IFRAME')window.__dsFsFix(n);else if(n.querySelectorAll)[].slice.call(n.querySelectorAll('iframe')).forEach(window.__dsFsFix);});});}).observe(document.documentElement,{childList:true,subtree:true});}catch(e){}"
			+ "window.__dsSub=function(){var t='';var segs=document.querySelectorAll('.ytp-caption-segment');if(segs.length){"
			// YouTube: only the lines actually visible (excludes lines scrolled out of / not yet entered into the rollup window, and hidden windows)
			+ "for(var i=0;i<segs.length;i++){var sg=segs[i];var r=sg.getBoundingClientRect();if(r.width<1||r.height<1)continue;"
			// every ancestor from the segment up to the window must be visible (lines fading in: opacity 0 on an ancestor)
			+ "var w=sg.closest('.caption-window');var ok=true;var el=sg;while(el){var st=getComputedStyle(el);if(st.display==='none'||st.visibility==='hidden'||parseFloat(st.opacity)<0.05){ok=false;break;}if(el===w)break;el=el.parentElement;}if(!ok)continue;"
			+ "if(w){var wr=w.getBoundingClientRect();if(r.top<wr.top-2||r.bottom>wr.bottom+2)continue;}"
			// really on screen: the element at the segment's centre must be the segment itself (or its line) (clipped/shifted lines are dropped)
			+ "var cx=Math.min(innerWidth-1,Math.max(0,r.left+r.width/2)),cy=Math.min(innerHeight-1,Math.max(0,r.top+r.height/2));var hit=document.elementFromPoint(cx,cy);"
			+ "if(!hit||!(sg.contains(hit)||hit===sg.parentElement||(sg.parentElement&&hit===sg.parentElement.parentElement)))continue;"
			+ "t+=(t?' ':'')+sg.textContent;}return t.trim();}"
			+ "if(location.hostname.indexOf('youtube.com')>=0)return '';"
			+ "var v=window.__dsVid();if(!v)return '';"
			+ "if(v.textTracks){for(var i=0;i<v.textTracks.length;i++){var tr=v.textTracks[i];if(tr.mode==='disabled'||(tr.kind!=='subtitles'&&tr.kind!=='captions'))continue;var cs=tr.activeCues;if(cs&&cs.length){for(var j=0;j<cs.length;j++){t+=(t?' ':'')+(cs[j].text||'');}if(t)return t.replace(/<[^>]+>/g,'').trim();}}}"
			+ "var vr=v.getBoundingClientRect();var va=vr.width*vr.height;var els=document.querySelectorAll('[class*=caption],[class*=subtitle],[class*=Caption],[class*=Subtitle],[id*=caption],[id*=subtitle],[class*=text-track],[class*=-cue],[class*=_cue],[class*=Cue],[class*=altyaz],[id*=altyaz]');"
			+ "for(var k=0;k<els.length;k++){var e=els[k];if(e.tagName==='VIDEO'||e.tagName==='TRACK'||e.tagName==='BUTTON'||e.contains(v))continue;var r=e.getBoundingClientRect();if(r.width<40||r.height<8||r.width*r.height>va*0.6)continue;if(r.right<vr.left||r.left>vr.right||r.bottom<vr.top||r.top>vr.bottom)continue;"
			+ "var cid=(e.getAttribute('class')||'')+' '+(e.id||'');if(/control|chrome|toolbar|menu|setting|progress|time|button|icon|title|header|thumb|badge/i.test(cid))continue;"
			+ "var st=getComputedStyle(e);if(st.visibility==='hidden'||st.display==='none'||st.opacity==='0')continue;var s=(e.innerText||'').trim();if(!s||s.length>300||s.indexOf('\\n\\n')>=0)continue;if(/^[\\d:\\s\\/.,\\-]+$/.test(s))continue;return s;}return '';};"
			+ "window.__dsLastSub='';window.__dsLastSubAt=0;"
			+ "window.__dsSubTick=function(){try{var s=window.__dsSub();if(s.length>300)s=s.slice(0,300);var now=Date.now();"
			+ "if(s!==window.__dsLastSub||(s&&now-window.__dsLastSubAt>2500)){window.__dsLastSub=s;window.__dsLastSubAt=now;console.log('__DS__'+JSON.stringify({s:s}));}"
			+ "var v=window.__dsVid();if(v&&v.textTracks&&!v.__dsCue){v.__dsCue=1;for(var i=0;i<v.textTracks.length;i++){v.textTracks[i].addEventListener('cuechange',window.__dsSubTick);}}"
			+ "var cw=document.querySelector('.ytp-caption-window-container');if(cw&&!cw.__dsObs){cw.__dsObs=1;new MutationObserver(window.__dsSubTick).observe(cw,{childList:true,subtree:true,characterData:true});}"
			+ "}catch(e){}};setInterval(window.__dsSubTick,100);"
			// Text field focus: 1 only if a visible field was clicked recently (within 1.5 s); stays 1 as long as the focus lasts.
			// (Hidden fields the site focuses on its own must not grab the keyboard; after ESC the earlier click must not grab it again.)
			+ "if(!window.__dsFocusHook){window.__dsFocusHook=1;window.__dsEdit=function(){var el=document.activeElement;if(!el)return 0;var tg=el.tagName;var ed=(tg==='TEXTAREA'||el.isContentEditable||(tg==='INPUT'&&!/^(button|submit|checkbox|radio|range|file|color|image|reset|hidden)$/i.test(el.type||'')));if(!ed)return 0;"
			+ "var r=el.getBoundingClientRect();if(r.width<4||r.height<4||r.bottom<0||r.right<0||r.top>innerHeight||r.left>innerWidth)return 0;if(window.__dsLastFocus===1)return 1;"
			+ "var cp=window.__dsClickPt;if(!cp||Date.now()-cp[2]>1500)return 0;if(cp[0]<r.left-6||cp[0]>r.right+6||cp[1]<r.top-6||cp[1]>r.bottom+6)return 0;return 1;};"
			// Drag and drop: when the crosshair slips, an image/link drag must not start (the drag mode swallows clicks)
			+ "document.addEventListener('dragstart',function(e){e.preventDefault();},true);"
			+ "window.__dsFocusSend=function(){var f=window.__dsEdit();if(f!==window.__dsLastFocus){window.__dsLastFocus=f;console.log('__DS__{\"focus\":'+f+'}');}};"
			+ "document.addEventListener('focusin',window.__dsFocusSend,true);document.addEventListener('focusout',function(){setTimeout(window.__dsFocusSend,60);},true);}"
			+ "}";

	public static String reporterJs() {
		// The skipper flag sits outside the guard: a setting change applies without reloading the page
		return REPORT_JS + "window.__dsAdSkip=" + DoomscrollConfig.get().adBlock + ";" + CINEMA_MSG_JS;
	}

	/**
	 * In-page ad cleaner. Injected separately into every frame (including the player iframe), sets up its own
	 * 1 s loop (idempotent). Rules: links and images that point to betting/casino sites or contain "deneme bonusu /
	 * bahis / casino" (Turkish betting-ad phrases); non-video iframes at standard ad sizes; click-trap layers over
	 * the video (carrying a link/onclick, or empty with a z-index). Player class names (ytp, vjs, jw, plyr,
	 * artplayer...) are preserved. Stops with window.__dsAdSkip=false.
	 */
	private static final String AD_CLEAN_JS =
			"if(!window.__dsVid){window.__dsVid=function(){var best=null,bs=-1;[].slice.call(document.querySelectorAll('video')).forEach(function(v){if(!(v.duration>0))return;var r=v.getBoundingClientRect();var sc=r.width*r.height+(v.paused?0:1e7);if(sc>bs){bs=sc;best=v;}});return best;};}"
			+ "window.__dsAdClean=function(){try{if(window.__dsAdSkip===false)return;"
			+ "var BETH=/bahis|casino|kumar|jackpot|rulet|slotin|betorspin|betist|betine|baywin|meritbet|jetbahis|marsbahis|sekabet|matbet|holiganbet|grandpashabet|casinomaxi|mobilbahis|bets10|betboo|superbetin|tipobet|restbet|piabet|betpas|onwin|hilbet|kralbet|betturkey|vdcasino|betnano|betwoon|betcio|sahabet|elexbet|imajbet|milanobet|betsmove|1xbet|betwinner|melbet|22bet|mostbet|pin-?up|1win|parimatch|freespin|deneme-?bonus|\\d+bet\\b|bet\\d+/i;"
			+ "var BETT=/deneme bonusu|ilk yat[ıi]r[ıi]m|yat[ıi]r[ıi]m bonus|bonusu|bahis|casino|kumar|freespin|free spin|spor bahis/i;"
			+ "var SAFE=/(^|\\.)(youtube|youtu|google|facebook|twitter|x|instagram|tiktok|reddit|wikipedia|netflix|imdb|twitch|kick|vimeo|dailymotion)\\.[a-z]+$/;if(SAFE.test(location.hostname.toLowerCase()))return;"
			+ "var ADPATH=/reklam|banner|sponsor|\\/go\\/|redirect|\\/click|out\\?|\\/ad\\/|\\/ads\\/|\\/r\\/|\\/link\\/|affiliate|promo/i;"
			+ "var SKIPC=/skip|atla|geç|gec\\b|kapat|close/i;"
			+ "function site(h){var p=h.split('.');return p.length>=2?p[p.length-2]+'.'+p[p.length-1]:h;}"
			+ "var mySite=site(location.hostname.toLowerCase());"
			+ "function hasSkip(e){return SKIPC.test((e.innerText||'').slice(0,200))||!!e.querySelector('[class*=skip],[class*=Skip],[id*=skip],[class*=close],[class*=kapat]');}"
			+ "function hide(e){if(!e||e.__dsHid)return;e.__dsHid=1;e.style.setProperty('display','none','important');var p=e.parentElement;if(p&&p!==document.body&&p.children.length===1&&!(p.innerText||'').trim()){p.__dsHid=1;p.style.setProperty('display','none','important');}}"
			// links
			+ "var links=document.querySelectorAll('a[href]');for(var i=0;i<links.length;i++){var a=links[i];if(a.__dsHid)continue;if(a.querySelector('video,iframe'))continue;var h='';try{h=new URL(a.href,location.href).hostname.toLowerCase();}catch(e){}"
			+ "var extSite=h&&site(h)!==mySite;var imgs=a.querySelectorAll('img');var alt='';for(var j=0;j<imgs.length;j++){alt+=' '+(imgs[j].alt||'')+' '+(imgs[j].src||'');}"
			+ "var txt=(a.innerText||'').trim();var imgOnly=imgs.length>0&&!txt;var rel=(a.getAttribute('rel')||'').toLowerCase();"
			+ "if((extSite&&BETH.test(h)&&!SAFE.test(h))||BETT.test(txt+' '+(a.title||''))||(imgs.length&&BETH.test(alt))||(imgOnly&&extSite&&!SAFE.test(h))||(imgOnly&&ADPATH.test(a.href))||(imgOnly&&/sponsored|nofollow/.test(rel)&&extSite)){hide(a);}}"
			// images
			+ "var ims=document.querySelectorAll('img');for(var k=0;k<ims.length;k++){var im=ims[k];if(im.__dsHid)continue;var sv=(im.src||'')+' '+(im.alt||'');if(BETH.test(sv)||BETT.test(im.alt||'')||ADPATH.test(im.src||'')){hide(im.closest('a')||im);}}"
			// boxes with ad/sponsor class names (when they contain a link or image but no video)
			+ "var boxes=document.querySelectorAll('[class*=reklam],[id*=reklam],[class*=sponsor],[id*=sponsor],[class*=adsbox],[class*=ad-banner],[class*=banner-ad],[class*=adsbygoogle],ins.adsbygoogle');"
			+ "for(var b=0;b<boxes.length;b++){var bx=boxes[b];if(bx.__dsHid||bx.querySelector('video')||bx.tagName==='BODY'||bx.tagName==='HTML')continue;if(bx.querySelector('a,img,iframe')||bx.tagName==='INS'){hide(bx);}}"
			// the video and the skip-ad button
			+ "var v=window.__dsVid();var vr=v?v.getBoundingClientRect():null;"
			+ "var sizes={'300x250':1,'336x280':1,'728x90':1,'970x90':1,'970x250':1,'160x600':1,'300x600':1,'320x50':1,'320x100':1,'468x60':1,'250x250':1,'200x200':1,'120x600':1,'300x50':1,'980x120':1,'930x180':1};"
			+ "var ifr=document.querySelectorAll('iframe');for(var i=0;i<ifr.length;i++){var f=ifr[i];if(f.__dsHid)continue;var r=f.getBoundingClientRect();var key=Math.round(r.width)+'x'+Math.round(r.height);var src=(f.src||'').toLowerCase();"
			+ "var vid=/youtube|youtu\\.be|vimeo|dailymotion|twitch|player|embed|video|stream|ok\\.ru|vk\\.com|sibnet|mail\\.ru|drive\\.google|hls|m3u8|kick\\.com/.test(src);"
			+ "if((sizes[key]&&!vid)||(BETH.test(src)&&!vid)){hide(f);}}"
			// trap covering the video: if it contains a skip button, do not hide it but make it unclickable (the button stays clickable)
			+ "if(vr&&vr.width>200){var all=document.querySelectorAll('a,div,span');for(var k=0;k<all.length;k++){var e=all[k];if(e.__dsHid||e.__dsPe||e.id==='__dsFsOv')continue;if(e.querySelector&&e.querySelector('video'))continue;"
			+ "var st=getComputedStyle(e);if(st.position!=='absolute'&&st.position!=='fixed')continue;if(st.display==='none'||st.visibility==='hidden'||st.pointerEvents==='none')continue;"
			+ "var er=e.getBoundingClientRect();if(er.width<vr.width*0.6||er.height<vr.height*0.6)continue;"
			+ "var ov=Math.max(0,Math.min(er.right,vr.right)-Math.max(er.left,vr.left))*Math.max(0,Math.min(er.bottom,vr.bottom)-Math.max(er.top,vr.top));if(ov<vr.width*vr.height*0.5)continue;"
			+ "var cls=(e.className||'')+' '+(e.id||'');if(/player|control|ytp|vjs|jw-|plyr|poster|overlay-play|artplayer|dplayer|progress|volume/i.test(cls))continue;"
			+ "var isLink=e.tagName==='A'||e.getAttribute('onclick')||e.querySelector('a[target=_blank]');var empty=!(e.innerText||'').trim()&&!e.querySelector('img,svg,button,input,video,iframe');var z=parseInt(st.zIndex)||0;"
			+ "if(!(isLink||(empty&&z>0)))continue;"
			+ "if(hasSkip(e)){e.__dsPe=1;e.style.setProperty('pointer-events','none','important');var ks=e.querySelectorAll('button,a,div,span');for(var q=0;q<ks.length;q++){var kk=ks[q];if(SKIPC.test((kk.innerText||'').slice(0,60))||/skip|close|kapat/i.test((kk.className||'')+' '+(kk.id||''))){kk.style.setProperty('pointer-events','auto','important');}}}"
			+ "else{hide(e);}}}"
			// auto-press the skip-ad button ("reklam gec" / "skip" / "atla")
			+ "var sk=document.querySelectorAll('button,a,div,span');var now=Date.now();for(var i2=0;i2<sk.length;i2++){var e2=sk[i2];var t2=(e2.innerText||'').trim();if(t2.length>40||e2.children.length>3)continue;var c2=(e2.className||'')+' '+(e2.id||'');"
			+ "var byText=/^(reklam[ıi]?\\s*)?(geç|gec|atla|skip)(\\s*(ads?|reklam[ıi]?|reklamlar[ıi]?|video))?\\s*[»›>→]*$/i.test(t2)||/^skip\\s*ads?\\s*[»›>→]*$/i.test(t2);var byCls=/skip[-_]?(ad|button|btn)|ima-skip|vast-skip|videoAdUiSkip|ad-?skip|skip-?ad|reklam[-_]?gec|reklami?-?gec/i.test(c2);"
			+ "if(!(byText||byCls))continue;var r2=e2.getBoundingClientRect();if(r2.width<8||r2.height<8||r2.width>innerWidth*0.5)continue;if(!vr||r2.right<vr.left-40||r2.left>vr.right+40||r2.bottom<vr.top-40||r2.top>vr.bottom+40)continue;var s2=getComputedStyle(e2);if(s2.display==='none'||s2.visibility==='hidden')continue;"
			+ "if(!e2.__dsClk||now-e2.__dsClk>800){e2.__dsClk=now;try{e2.click();}catch(x){}}}"
			+ "}catch(e){}};"
			+ "if(!window.__dsCleanTimer){window.__dsCleanTimer=setInterval(window.__dsAdClean,1000);window.__dsAdClean();}";

	/** The cleaner to inject into every frame + the setting flag. */
	public static String adCleanJs() {
		return AD_CLEAN_JS + "window.__dsAdSkip=" + DoomscrollConfig.get().adBlock + ";";
	}

	/** Tablet: install the ad cleaner in all frames (including the player iframe). */
	public static void tabletAdClean() {
		CefBrowserView b = tablet;
		if (b == null || !DoomscrollConfig.get().adBlock) {
			return;
		}
		jsAllFrames(b, adCleanJs());
		b.applyCosmetics();
	}

	/** Runs the code in all of the browser's frames (main + iframes). */
	public static void jsAllFrames(CefBrowserView b, String code) {
		var cb = b.getCefBrowser();
		try {
			for (String id : cb.getFrameIdentifiers()) {
				var f = cb.getFrameByIdentifier(id);
				if (f != null) {
					f.executeJavaScript(code, f.getURL(), 0);
				}
			}
		} catch (Exception e) {
			cb.executeJavaScript(code, cb.getURL(), 0);
		}
	}

	public static void toggleCinema() {
		ScreenBrowsers.toggleCinemaActive();
	}

	public static void toggleTabletCinema() {
		cinemaToggle(tablet, tabletCinema);
	}

	/** Called every ~2 s: installs the watcher when auto-advance is on and the page is a short-form video page (idempotent). */
	public static void tickAutoNext() {
		if (tablet != null) {
			jsAllFrames(tablet, reporterJs()); // time/title report (idempotent)
		}
		if (!DoomscrollConfig.get().autoScroll) return;
		if (tablet != null && isShortFormPage(tabletUrl())) tabletJs(AUTO_NEXT_JS);
		tabletAdClean();
	}

	/** Used by ScreenBrowsers per screen. */
	public static String autoNextJs() {
		return AUTO_NEXT_JS;
	}

	/** Status summary for /ds debug. */
	public static String debugInfo() {
		var init = CefService.initialize();
		return "mcef=" + init.getStage() + " %" + (int) init.getPercentage() + " " + ScreenBrowsers.debugInfo()
				+ "\n  tablet=" + (tablet != null) + " screenVolume=" + getUserVolume() + (isMuted() ? "(muted)" : "") + " tabletVolume=" + getTabletVolume() + (isTabletMuted() ? "(muted)" : "");
	}

	@Nullable
	public static CefBrowserView getIfPresent() {
		return ScreenBrowsers.activeBrowser();
	}

	public static void close() {
		ScreenBrowsers.closeAll();
	}

	/** Loads directly without any processing (for the local player page). */
	public static void navigateRaw(String url) {
		CefBrowserView b = getOrCreate();
		if (b != null) {
			b.getCefBrowser().loadURL(url);
		}
	}

	/** Turns user input into an address (search text -> search page); "" when invalid. */
	public static String normalize(String input) {
		return normalizeUrl(input);
	}

	public static void navigate(String input) {
		String url = normalizeUrl(input);
		if (url.isEmpty()) {
			return;
		}
		BlockPos anchor = ScreenBrowsers.activeAnchor();
		if (anchor == null) {
			return;
		}
		// Server-first: the address goes to the server (control is taken), everyone's screen - ours included - loads from there
		ScreenBrowsers.requestNavigate(anchor, url);
	}

	/** Turns user text into an address: without "://", https:// if it looks like a domain, otherwise a search. */
	public static String normalizeUrl(String input) {
		String url = input == null ? "" : input.trim();
		if (url.isEmpty()) {
			return "";
		}
		if (!url.contains("://")) {
			url = url.contains(".") && !url.contains(" ") ? "https://" + url : searchUrl(url);
		}
		return url;
	}

	public static String searchUrl(String query) {
		return "https://www.google.com/search?q=" + java.net.URLEncoder.encode(query.trim(), java.nio.charset.StandardCharsets.UTF_8);
	}

	/** Always opens the text as a search (even if it looks like a URL). */
	public static void search(String query) {
		if (query == null || query.isBlank()) {
			return;
		}
		BlockPos anchor = ScreenBrowsers.activeAnchor();
		if (anchor != null) {
			ScreenBrowsers.requestNavigate(anchor, searchUrl(query));
		}
	}

	public static void goBack() {
		ScreenBrowsers.noteExplicitActive();
		CefBrowserView b = getIfPresent();
		if (b != null && b.getCefBrowser().canGoBack()) {
			b.getCefBrowser().goBack();
		}
	}

	public static void goForward() {
		ScreenBrowsers.noteExplicitActive();
		CefBrowserView b = getIfPresent();
		if (b != null && b.getCefBrowser().canGoForward()) {
			b.getCefBrowser().goForward();
		}
	}

	public static void reload() {
		ScreenBrowsers.noteExplicitActive();
		CefBrowserView b = getIfPresent();
		if (b != null) {
			b.getCefBrowser().reload();
		}
	}

	public static String currentUrl() {
		CefBrowserView b = getIfPresent();
		if (b == null) {
			return "";
		}
		String u = b.getCefBrowser().getURL();
		return u == null ? "" : u;
	}

	/** Next/previous video on short-form video pages (reliable arrow key). */
	public static void nextVideo() {
		ScreenBrowsers.noteExplicitActive();
		runJs(NAV_JS + "window.__dsNext();");
	}

	public static void prevVideo() {
		ScreenBrowsers.noteExplicitActive();
		runJs(NAV_JS + "window.__dsPrev();");
	}

	public static void tabletNextVideo() {
		tabletJs(NAV_JS + "window.__dsNext();");
	}

	public static void tabletPrevVideo() {
		tabletJs(NAV_JS + "window.__dsPrev();");
	}

	public static void togglePlayback() {
		ScreenBrowsers.noteExplicitActive();
		runJs("document.querySelectorAll('video,audio').forEach(function(m){ if (m.paused) { m.play(); } else { m.pause(); } });");
	}

	// ---- volume: screens (remote) and the tablet in hand are separate; both are written to the config ----

	/** Effective value in this session; -1 = not yet determined from the server policy. */
	private static float othersEffective = -1f;

	/** Volume of screens you did not place. If the server says "start muted", the session starts at 0. */
	public static float getOthersScreenVolume() {
		if (othersEffective < 0f) {
			othersEffective = ServerPolicy.muteOthers() ? 0f : DoomscrollConfig.get().othersScreenVolume;
		}
		return othersEffective;
	}

	/** off -> low -> medium -> full -> off */
	public static void cycleOthersScreenVolume() {
		float v = getOthersScreenVolume();
		float next = v <= 0.01f ? 0.35f : v <= 0.4f ? 0.7f : v <= 0.75f ? 1f : 0f;
		othersEffective = next;
		DoomscrollConfig.get().othersScreenVolume = next;
		DoomscrollConfig.save();
	}

	public static String othersScreenLabel() {
		return Lang.tr(com.doomscroll.ScreenBlockEntity.volumeKey(getOthersScreenVolume()));
	}

	/** Server policy changed: recompute the effective value. */
	public static void onPolicyChanged() {
		othersEffective = -1f;
	}

	public static float getUserVolume() { return DoomscrollConfig.get().screenVolume; }
	public static boolean isMuted() { return DoomscrollConfig.get().screenMuted; }

	public static void setUserVolume(float v) {
		DoomscrollConfig cfg = DoomscrollConfig.get();
		float n = Math.max(0f, Math.min(1f, v));
		if (n == cfg.screenVolume) {
			return;
		}
		cfg.screenVolume = n;
		DoomscrollConfig.save();
		lastAppliedVolume = -1f;
	}

	public static void volumeStep(float delta) {
		setUserVolume(Math.round((getUserVolume() + delta) * 10f) / 10f);
	}

	public static void toggleMute() {
		DoomscrollConfig cfg = DoomscrollConfig.get();
		cfg.screenMuted = !cfg.screenMuted;
		DoomscrollConfig.save();
		lastAppliedVolume = -1f;
	}

	/**
	 * Volume of the tablet in hand: its own level, independent of the screens (the speaker button on the tablet toolbar).
	 * Other players' tablets are a sound heard from the world, so they play at the screen level.
	 */
	public static float getTabletVolume() { return DoomscrollConfig.get().tabletVolume; }
	public static boolean isTabletMuted() { return DoomscrollConfig.get().tabletMuted; }

	public static void setTabletVolume(float v) {
		DoomscrollConfig cfg = DoomscrollConfig.get();
		float n = Math.max(0f, Math.min(1f, v));
		if (n == cfg.tabletVolume) {
			return;
		}
		cfg.tabletVolume = n;
		DoomscrollConfig.save();
	}

	/** Volume heard from other players' tablets (0 = off). Remote -> Settings -> "Others' tablets". */
	public static float getRemoteTabletVolume() { return DoomscrollConfig.get().remoteTabletVolume; }

	public static String remoteTabletLabel() {
		return Lang.tr(com.doomscroll.ScreenBlockEntity.volumeKey(getRemoteTabletVolume()));
	}

	/** off -> low -> full -> off (labels are read from the same thresholds as the screen volume) */
	public static void cycleRemoteTabletVolume() {
		DoomscrollConfig cfg = DoomscrollConfig.get();
		cfg.remoteTabletVolume = cfg.remoteTabletVolume <= 0.01f ? 0.35f : cfg.remoteTabletVolume <= 0.5f ? 1f : 0f;
		DoomscrollConfig.save();
	}

	public static void toggleTabletMute() {
		DoomscrollConfig cfg = DoomscrollConfig.get();
		cfg.tabletMuted = !cfg.tabletMuted;
		DoomscrollConfig.save();
	}

	private static long lastScreenSeenNanos = 0L;
	private static boolean idlePaused = false;
	private static final long IDLE_PAUSE_NANOS = 2_000_000_000L;
	private static final long IDLE_CLOSE_NANOS = 15_000_000_000L;

	/** While the tablet/GUI is open: reset the idle counters so the browser does not close. */
	public static void keepAlive() {
	}

	/** Called by the renderer every frame it draws a screen that is on. */
	public static void noteScreen(BlockPos pos) {
	}

	/** Renderer: a screen that is off was drawn. If no other screen is on, stop + mute immediately. */
	public static void noteScreenOff(BlockPos pos) {
	}

	/** Distance * user volume (* mute). Called rarely. Stops when there is no screen, closes when there has been none for a long time. */
	public static void updateVolume(Vec3 playerPos) {
	}

	private static void runJs(String code) {
		CefBrowserView b = getIfPresent();
		if (b != null) {
			b.getCefBrowser().executeJavaScript(code, b.getCefBrowser().getURL(), 0);
		}
	}

	public static GpuSampler sampler() {
		if (sampler == null) {
			sampler = RenderSystem.getDevice().createSampler(
					AddressMode.CLAMP_TO_EDGE,
					AddressMode.CLAMP_TO_EDGE,
					FilterMode.LINEAR,
					FilterMode.LINEAR,
					1,
					OptionalDouble.empty()
			);
		}
		return sampler;
	}

	public static float initProgress() {
		return CefService.initialize().getPercentage();
	}
}
