"""Doomscroll pixel art: block/item textures, GUI icons and the mod icon (close to the vanilla palette)."""
import os
from PIL import Image  # pip install pillow

A = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "src", "main", "resources", "assets", "doomscroll")
TEX = A + "/textures"

PAL = {
    ".": None,
    "K": (11, 11, 14, 255),      # outline
    "D": (30, 30, 35, 255),      # dark body / shadow
    "B": (44, 44, 51, 255),      # body
    "L": (61, 61, 70, 255),      # light body
    "H": (89, 89, 99, 255),      # highlight
    "G": (154, 154, 166, 255),   # light gray (button)
    "g": (110, 110, 122, 255),   # mid gray
    "W": (232, 232, 238, 255),   # white
    "R": (217, 67, 59, 255),     # red (power)
    "r": (140, 35, 31, 255),     # dark red
    "A": (63, 141, 224, 255),    # blue
    "a": (34, 88, 154, 255),     # dark blue
    "E": (79, 191, 107, 255),    # green
    "e": (39, 110, 58, 255),     # dark green
    "S": (7, 8, 12, 255),        # screen glass
    "s": (18, 21, 31, 255),      # glass glare
    "t": (13, 15, 22, 255),      # glass upper tone
    "u": (4, 5, 8, 255),         # glass lower tone
    "Y": (226, 176, 74, 255),    # yellow LED
}


def paint(rows, path, scale=1):
    h = len(rows)
    w = len(rows[0])
    im = Image.new("RGBA", (w, h), (0, 0, 0, 0))
    px = im.load()
    for y, row in enumerate(rows):
        assert len(row) == w, "row width: " + path + " row " + str(y)
        for x, ch in enumerate(row):
            c = PAL[ch]
            if c is not None:
                px[x, y] = c
    if scale != 1:
        im = im.resize((w * scale, h * scale), Image.NEAREST)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    im.save(path)
    print("wrote", os.path.relpath(path, A), im.size)


# ---------------- screen block ----------------
screen_front = [
    "KKKKKKKKKKKKKKKK",
    "KHLLLLLLLLLLLLBK",
    "KLtttttttttttttDK"[:16],
]
screen_front = [
    "KKKKKKKKKKKKKKKK",
    "KHLLLLLLLLLLLLBK",
    "KLttttttttttttDK",
    "KLsSttttttttttDK",
    "KLSsSSSSSSSSSSDK",
    "KLSSSSSSSSSSSSDK",
    "KLSSSSSSSSSSSSDK",
    "KLSSSSSSSSSSSSDK",
    "KLSSSSSSSSSSSSDK",
    "KLSSSSSSSSSSSSDK",
    "KLuuuuuuuuuuuuDK",
    "KLuuuuuuuuuuuuDK",
    "KLBBBBBBBBBBBBDK",
    "KLBBBBBBBBBRBBDK",
    "KBDDDDDDDDDDDDDK",
    "KKKKKKKKKKKKKKKK",
]
paint(screen_front, TEX + "/block/screen.png")

# Off panel: the renderer covers the whole panel with a single quad; plain glass so no pattern gets stretched
paint(["S" * 16] * 16, TEX + "/block/screen_off.png")

screen_side = [
    "DDDDDDDDDDDDDDDD",
    "DHHHHHHHHHHHHHHD",
    "DLLLLLLLLLLLLLLD",
    "DBBBBBBBBBBBBBBD",
    "DBBBBBBBBBBBBBBD",
    "DBDDDDDDDDDDDDBD",
    "DBBBBBBBBBBBBBBD",
    "DBDDDDDDDDDDDDBD",
    "DBBBBBBBBBBBBBBD",
    "DBDDDDDDDDDDDDBD",
    "DBBBBBBBBBBBBBBD",
    "DBBBBBBBBBBBBBBD",
    "DBBBBBBBBBBBBBBD",
    "DDDDDDDDDDDDDDDD",
    "DKKKKKKKKKKKKKKD",
    "DDDDDDDDDDDDDDDD",
]
paint(screen_side, TEX + "/block/screen_side.png")

screen_back = [
    "DDDDDDDDDDDDDDDD",
    "DLLLLLLLLLLLLLLD",
    "DLBBBBBBBBBBBBDD",
    "DLBDBDBDBDBDBBDD",
    "DLBDBDBDBDBDBBDD",
    "DLBDBDBDBDBDBBDD",
    "DLBDBDBDBDBDBBDD",
    "DLBBBBBBBBBBBBDD",
    "DLBBBBBBBBBBBBDD",
    "DLBKKKKBBKKBBBDD",
    "DLBKAAKBBKKBBBDD",
    "DLBKKKKBBKKBBBDD",
    "DLBBBBBBBBBBBBDD",
    "DLBBBBBBBBBBBBDD",
    "DDDDDDDDDDDDDDDD",
    "DDDDDDDDDDDDDDDD",
]
paint(screen_back, TEX + "/block/screen_back.png")

# ---------------- remote ----------------
remote_icon = [
    "....KKKKKKK.....",
    "...KHLLLLLDK....",
    "...KLBRRBBDK....",
    "...KLBrrBBDK....",
    "...KLBBBBBDK....",
    "...KLBGGGBDK....",
    "...KLGGWGGDK....",
    "...KLBGGGBDK....",
    "...KLBBBBBDK....",
    "...KLABBEBDK....",
    "...KLaBBeBDK....",
    "...KLBBBBBDK....",
    "...KLgBgBgDK....",
    "...KLBBBBBDK....",
    "...KDgggggDK....",
    "....KKKKKKK.....",
]
paint(remote_icon, TEX + "/item/remote_icon.png")

# The texture of the 3D in-hand model (remote_model.png) is generated by tools/make_remote_model.py.

# ---------------- tablet ----------------
tablet_icon = [
    "................",
    "................",
    ".KKKKKKKKKKKKKK.",
    "KHLLLLLLgLLLLLBK",
    "KLttttttttttttDK",
    "KLsSttttttttttDK",
    "KLSsSSSSSSSSSSDK",
    "KLSSSSSSSSSSSSDK",
    "KLSSSSSSSSSSSSDK",
    "KLuuuuuuuuuuuuDK",
    "KLBBBBBBBBBBBBDK",
    "KBDDDDDDgDDDDDDK",
    ".KKKKKKKKKKKKKK.",
    "................",
    "................",
    "................",
]
paint(tablet_icon, TEX + "/item/tablet_icon.png")

# ---------------- GUI icons (9x9, white; tinted when drawn) ----------------
ICONS = {
    "power": [
        "....W....",
        "....W....",
        "..W.W.W..",
        ".W.....W.",
        "W.......W",
        "W.......W",
        ".W.....W.",
        "..WWWWW..",
        ".........",
    ],
    "speaker": [
        ".........",
        "....W....",
        "...WW.W..",
        ".WWWW.W.W",
        ".WWWW.W.W",
        ".WWWW.W.W",
        "...WW.W..",
        "....W....",
        ".........",
    ],
    "speaker_off": [
        ".........",
        "....W....",
        "...WW....",
        ".WWWW.W.W",
        ".WWWW..W.",
        ".WWWW.W.W",
        "...WW....",
        "....W....",
        ".........",
    ],
    "back": [
        ".........",
        "...W.....",
        "..WW.....",
        ".WWWWWWW.",
        "WWWWWWWWW",
        ".WWWWWWW.",
        "..WW.....",
        "...W.....",
        ".........",
    ],
    "forward": [
        ".........",
        ".....W...",
        ".....WW..",
        ".WWWWWWW.",
        "WWWWWWWWW",
        ".WWWWWWW.",
        ".....WW..",
        ".....W...",
        ".........",
    ],
    "reload": [
        "...WWW...",
        ".WW...WWW",
        ".W.....WW",
        "W.......W",
        "W........",
        "W........",
        ".W.....W.",
        ".WW...WW.",
        "...WWW...",
    ],
    "home": [
        "....W....",
        "...WWW...",
        "..WWWWW..",
        ".WWWWWWW.",
        "WWWWWWWWW",
        "..WWWWW..",
        "..WW.WW..",
        "..WW.WW..",
        "..WW.WW..",
    ],
    "cinema": [
        "WWW...WWW",
        "W.......W",
        "W.......W",
        ".........",
        ".........",
        ".........",
        "W.......W",
        "W.......W",
        "WWW...WWW",
    ],
    "plus": [
        ".........",
        "...WWW...",
        "...WWW...",
        "...WWW...",
        "WWWWWWWWW",
        "...WWW...",
        "...WWW...",
        "...WWW...",
        ".........",
    ],
    "to_tablet": [
        ".....WWWW",
        ".....W..W",
        "W....W..W",
        "WW...W..W",
        "WWW..W..W",
        "WW...W..W",
        "W....W..W",
        ".....W..W",
        ".....WWWW",
    ],
    "cast": [
        ".........",
        ".........",
        "W...WWWWW",
        "WW..W...W",
        "WWW.W...W",
        "WW..W...W",
        "W...WWWWW",
        "......W..",
        ".....WWW.",
    ],
    "star": [
        ".WWWWWWW.",
        ".W.....W.",
        ".W.....W.",
        ".W.....W.",
        ".W.....W.",
        ".W.....W.",
        ".W..W..W.",
        ".W.W.W.W.",
        ".WW...WW.",
    ],
    "star_filled": [
        ".WWWWWWW.",
        ".WWWWWWW.",
        ".WWWWWWW.",
        ".WWWWWWW.",
        ".WWWWWWW.",
        ".WWWWWWW.",
        ".WWW.WWW.",
        ".WW...WW.",
        ".W.....W.",
    ],
    "menu": [
        ".........",
        ".WWWWWWW.",
        ".........",
        ".WWWWWWW.",
        ".........",
        ".WWWWWWW.",
        ".........",
        ".WWWWWWW.",
        ".........",
    ],
    "close": [
        ".........",
        ".W.....W.",
        ".WW...WW.",
        "..WW.WW..",
        "...WWW...",
        "..WW.WW..",
        ".WW...WW.",
        ".W.....W.",
        ".........",
    ],
    "play": [
        ".W.......",
        ".WW......",
        ".WWW.....",
        ".WWWW....",
        ".WWWWW...",
        ".WWWW....",
        ".WWW.....",
        ".WW......",
        ".W.......",
    ],
    "trash": [
        "...WWW...",
        ".WWWWWWW.",
        ".........",
        ".WWWWWWW.",
        ".W.W.W.W.",
        ".W.W.W.W.",
        ".W.W.W.W.",
        ".W.....W.",
        ".WWWWWWW.",
    ],
    "clock": [
        "...WWW...",
        ".WW...WW.",
        ".W..W..W.",
        "W...W...W",
        "W...WWW.W",
        "W.......W",
        ".W.....W.",
        ".WW...WW.",
        "...WWW...",
    ],
    "queue": [
        ".WWWWWWW.",
        ".........",
        ".WWWWWWW.",
        ".........",
        ".WWWWW.W.",
        "......WW.",
        ".WWWWWWWW",
        "......WW.",
        ".WWWWW.W.",
    ],
    "tv": [
        "WWWWWWWWW",
        "W.......W",
        "W.......W",
        "W.......W",
        "W.......W",
        "W.......W",
        "WWWWWWWWW",
        "...W.W...",
        "..WWWWW..",
    ],
    "search": [
        "..WWW....",
        ".W...W...",
        ".W...W...",
        ".W...W...",
        "..WWW....",
        "....WW...",
        ".....WW..",
        "......WW.",
        ".........",
    ],
    "go": [
        ".........",
        ".....W...",
        ".....WW..",
        ".WWWWWWW.",
        "WWWWWWWWW",
        ".WWWWWWW.",
        ".....WW..",
        ".....W...",
        ".........",
    ],
    "lock": [
        "...WWW...",
        "..W...W..",
        "..W...W..",
        ".WWWWWWW.",
        ".W.....W.",
        ".W..W..W.",
        ".W..W..W.",
        ".W.....W.",
        ".WWWWWWW.",
    ],
    "broadcast": [
        ".........",
        "..W...W..",
        ".W.....W.",
        "W...W...W",
        "W..WWW..W",
        "W...W...W",
        ".W.....W.",
        "..W...W..",
        ".........",
    ],
}
for name, rows in ICONS.items():
    paint(rows, TEX + "/gui/sprites/icon/" + name + ".png")

# Mod icon (Modrinth 512x512) lives in a separate script: tools/make_icon.py
print("done")
