package com.doomscroll;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * config/doomscroll-server.txt: ayar dosyasinin yanina konan aciklama metni.
 *
 * <p>JSON'a yorum yazilamadigi icin yonetici ham dosyayi acinca yalnizca anahtar adlarini goruyor.
 * Bu dosya her acilista yeniden yazilir, yani mod guncellendiginde aciklamalar da guncel kalir.
 * Icerik iki dilde; sunucu tarafinda dil dosyasi yuklu olmadigi icin metin burada duruyor.
 */
final class ServerGuide {
	private ServerGuide() {}

	static void write(Path configDir) {
		Path file = configDir.resolve("doomscroll-server.txt");
		try {
			Files.createDirectories(configDir);
			Files.writeString(file, TEXT, StandardCharsets.UTF_8);
		} catch (IOException e) {
			Doomscroll.LOGGER.warn("doomscroll-server.txt yazilamadi: {}", e.toString());
		}
	}

	private static final String TEXT = String.join("\n",
			"doomscroll - server settings / sunucu ayarlari",
			"==============================================",
			"",
			"This file is regenerated on every start. Edit doomscroll-server.json, not this one.",
			"Bu dosya her acilista yeniden yazilir. Duzenlemen gereken dosya doomscroll-server.json.",
			"",
			"In game, /doomscroll help lists the same settings with their current values, and every",
			"change made with a command is saved and sent to all players at once - nobody has to rejoin.",
			"Oyun icinde /doomscroll yardim ayni ayarlari su anki degerleriyle listeler; komutla yapilan",
			"her degisiklik kaydedilir ve aninda butun oyunculara gider, kimsenin yeniden girmesi gerekmez.",
			"",
			"",
			"SAFETY AND MODERATION / GUVENLIK VE MODERASYON",
			"----------------------------------------------",
			"",
			"lockdown                      default false   /doomscroll emergency on|off",
			"  EN  Emergency shutdown. Every screen goes dark and none can be turned on. Use it when",
			"      something is on a screen that must stop right now.",
			"  TR  Acil kapatma. Butun ekranlar kararir ve hicbiri acilamaz. Ekranda hemen durmasi",
			"      gereken bir sey varsa bunu kullan.",
			"",
			"blockedDomains                default []      /doomscroll block <domain>",
			"  EN  These domains and their subdomains can never be opened. Blocking example.com also",
			"      blocks www.example.com and ads.example.com.",
			"  TR  Bu alan adlari ve alt alanlari hicbir ekranda acilamaz. example.com engellenince",
			"      www.example.com ve ads.example.com da engellenir.",
			"",
			"allowedDomains                default []      /doomscroll allow <domain>",
			"  EN  While this list is empty everything is allowed. The moment it has one entry, only",
			"      the listed domains can be opened. This is the strictest control you have.",
			"  TR  Bu liste bosken her yer serbest. Icine bir tane bile girdi koydugun an yalnizca",
			"      listedekiler acilabilir. Elindeki en siki denetim bu.",
			"",
			"allowPrivateNetwork           default false   /doomscroll privatenet on|off",
			"  EN  Keep this OFF. With it on, a player can put http://192.168.1.1 on a screen and every",
			"      viewer's client opens their own router page. Loopback, LAN ranges, link-local",
			"      (including cloud metadata) and dotless intranet names are all refused while it is off.",
			"  TR  Bunu KAPALI tut. Acik olsa bir oyuncu ekrana http://192.168.1.1 koyup her izleyicinin",
			"      kendi modem arayuzunu actirabilir. Kapaliyken loopback, yerel ag araliklari,",
			"      link-local (bulut metadata dahil) ve noktasiz ic ag adlari reddedilir.",
			"",
			"requireConsent                default false   /doomscroll consent on|off",
			"  EN  A page outside allowedDomains is not drawn. Instead the viewer sees a card naming the",
			"      domain and the player who placed the screen, with Show and Home menu. Until Show is",
			"      pressed the site receives no request at all, so neither shock content nor the viewer's",
			"      IP reaches it. The choice is remembered per domain for that session.",
			"      Turn this on for a public server. It is the single most convincing setting here.",
			"  TR  allowedDomains disindaki sayfa cizilmez. Yerine alan adini ve ekrani koyan oyuncuyu",
			"      yazan bir kart cikar; Goster ve Ana menu dugmeleri var. Goster'e basilana kadar siteye",
			"      hicbir istek gitmez, yani ne sok icerik ne de izleyicinin IP'si oraya ulasir. Secim o",
			"      oturum boyunca alan adi basina hatirlanir.",
			"      Halka acik sunucuda bunu ac. Buradaki en ikna edici ayar bu.",
			"",
			"separateScreenCookies         default false   /doomscroll cookies on|off",
			"  EN  Screens run on cookies kept in memory, separate from the persistent profile a player's",
			"      own tablet uses. A page somebody else opened then cannot see or use that player's",
			"      signed-in sessions. The cost: a sign-in made on a screen is lost when the game closes.",
			"      Each player also has this in their own client config; the server setting forces it on",
			"      for everyone. It applies to browsers opened after the change.",
			"  TR  Ekranlar, oyuncunun kendi tabletinin kullandigi kalici profilden ayri, bellekte tutulan",
			"      cerezlerle calisir. Baskasinin actigi bir sayfa o oyuncunun giris yapmis oturumlarini",
			"      goremez. Bedeli: ekranda yapilan giris oyun kapaninca kaybolur. Her oyuncunun kendi",
			"      istemci ayarinda da var; sunucu ayari herkes icin zorlar. Degisiklikten sonra acilan",
			"      tarayicilar icin gecerli olur.",
			"",
			"showDomain                    default true    /doomscroll showdomain on|off",
			"  EN  The real domain is shown on the HUD when a player looks at a screen. A page cannot",
			"      touch the game's interface, so a fake sign-in page cannot hide where it really is.",
			"  TR  Oyuncu ekrana bakinca gercek alan adi HUD'da yazar. Sayfa oyunun arayuzune dokunamaz,",
			"      yani sahte bir giris sayfasi nerede oldugunu gizleyemez.",
			"",
			"muteOthersByDefault           default false   /doomscroll muteothers on|off",
			"  EN  Screens a player did not place start silent for them. They can raise the slider in the",
			"      remote under More. Sensible on a public server, annoying among friends.",
			"  TR  Oyuncunun kendi koymadigi ekranlar onda sessiz baslar. Kumandadaki Diger sekmesinden",
			"      kaydiriciyi acabilir. Halka acik sunucuda mantikli, arkadas arasinda rahatsiz edici.",
			"",
			"",
			"AUDIT LOG / DENETIM KAYDI",
			"-------------------------",
			"",
			"auditLog                      default true    /doomscroll auditlog on|off",
			"  EN  Writes config/doomscroll-audit.log: every address opened, every blocked attempt, every",
			"      broadcast and every power change, with the player name and UUID, the time, the world",
			"      and the block. /doomscroll audit [n] shows the last n entries in chat.",
			"      Addresses are never used as a format string, so a % in a URL cannot break anything.",
			"  TR  config/doomscroll-audit.log dosyasina yazar: acilan her adres, engellenen her deneme,",
			"      her yayin ve her ac/kapat; oyuncu adi ve UUID'si, zaman, dunya ve blok ile. Son n kaydi",
			"      /doomscroll kayit [n] ile sohbette gorursun.",
			"      Adres hicbir zaman bicim dizesi olarak kullanilmaz, yani icinde % olan bir adres bir sey kiramaz.",
			"",
			"",
			"LIMITS / SINIRLAR",
			"-----------------",
			"",
			"maxPanelBlocks                default 0       /doomscroll maxpanel <blocks>",
			"  EN  Largest panel one player may build, in blocks. 0 means unlimited. Going over refunds",
			"      the block instead of placing it.",
			"  TR  Bir oyuncunun kurabilecegi en buyuk panel, blok olarak. 0 = sinirsiz. Sinir asilinca",
			"      blok konmaz, esya iade edilir.",
			"",
			"maxScreensPerPlayer           default 0       /doomscroll maxscreens <blocks>",
			"  EN  How many screen blocks one player may own. 0 means unlimited. Counted over loaded",
			"      chunks only.",
			"  TR  Bir oyuncunun sahip olabilecegi ekran blogu sayisi. 0 = sinirsiz. Yalnizca yuklu",
			"      chunk'lardakiler sayilir.",
			"",
			"urlCooldownMs                 default 0       /doomscroll cooldown <ms>",
			"  EN  Minimum gap between one player's address changes. 0 means none, which is right among",
			"      friends. 1000-2000 is a good value on a public server.",
			"  TR  Ayni oyuncunun iki adres degisikligi arasinda beklemesi gereken sure. 0 = beklemesiz,",
			"      arkadas arasinda dogrusu bu. Halka acik sunucuda 1000-2000 iyi bir deger.",
			"",
			"controlTimeoutSeconds         default 45      /doomscroll controltime <seconds>",
			"  EN  How long a controller who goes quiet keeps control of a screen.",
			"  TR  Sessiz kalan kontrolcunun ekranin kontrolunu ne kadar sure elinde tuttugu.",
			"",
			"",
			"FEATURE SWITCHES / OZELLIK IZINLERI",
			"-----------------------------------",
			"",
			"broadcast                     default true    /doomscroll broadcast on|off",
			"  EN  Broadcast mode relays one player's view of a screen to everyone looking at it, video",
			"      and audio. Costs the server roughly 150 KB/s per viewer. Turn it off if that matters.",
			"  TR  Yayin modu, bir oyuncunun ekrandaki goruntusunu sesiyle birlikte ayni ekrana bakan",
			"      herkese aktarir. Sunucuya izleyici basina yaklasik 150 KB/s yuk biner. Onemliyse kapat.",
			"",
			"pointer                       default true    /doomscroll pointer on|off",
			"  EN  Players see each other's cursors on a screen. At most ~16 positions per second, 48 blocks.",
			"  TR  Oyuncular birbirinin ekrandaki imlecini gorur. Saniyede en fazla ~16 konum, 48 blok.",
			"",
			"redstone                      default true    /doomscroll redstone on|off",
			"  EN  Whether a redstone signal may toggle a screen. Each screen's owner still has to enable",
			"      it per screen with /ds redstone.",
			"  TR  Redstone sinyalinin ekrani acip kapatabilmesi. Ekran sahibi ayrica her ekran icin",
			"      /ds redstone ile acmak zorunda.",
			"",
			"announce / announceRange      default true / 32   /doomscroll announce on|off",
			"  EN  The \"X opened this site on the screen\" notice and how far it reaches, in blocks.",
			"  TR  \"X ekranda su siteyi acti\" bildirimi ve kac blok uzaga ulastigi.",
			"",
			"screenLightLevel              default 12      /doomscroll light <0-15>",
			"  EN  Block light emitted by a screen that is on. Needs a restart to take effect.",
			"  TR  Acik ekranin yaydigi blok isigi. Etkili olmasi icin yeniden baslatmak gerekir.",
			"",
			"",
			"PERMISSIONS / IZINLER",
			"---------------------",
			"",
			"With a permission manager installed (anything speaking fabric-permissions-api, such as",
			"LuckPerms) these nodes are honoured. Without one, the first three are open to everyone and",
			"the last two require gamemaster. No extra dependency is needed either way.",
			"Bir izin yoneticisi kuruluysa (fabric-permissions-api konusan herhangi biri, LuckPerms gibi)",
			"su dugumler gecerli olur. Yoksa ilk ucu herkese acik, son ikisi oyun yoneticisine. Her iki",
			"durumda da ek bir bagimlilik gerekmez.",
			"",
			"  doomscroll.place        place screens / ekran koyabilme",
			"  doomscroll.url          change the address on a screen / ekranda adres degistirebilme",
			"  doomscroll.broadcast    start broadcast mode / yayin modu baslatabilme",
			"  doomscroll.bypass       ignore the domain rules and the limits / adres kurallarini ve sinirlari asabilme",
			"  doomscroll.admin        /doomscroll commands and report alerts / komutlar ve rapor bildirimleri",
			"",
			"",
			"THREE STARTING POINTS / UC BASLANGIC NOKTASI",
			"-------------------------------------------",
			"",
			"Friends, private server - leave everything at its default. Nothing gets in the way.",
			"Arkadaslar, ozel sunucu - her sey varsayilanda kalsin. Hicbir sey yoluna cikmaz.",
			"",
			"Public server, open internet:",
			"Halka acik sunucu, serbest internet:",
			"  /doomscroll consent on",
			"  /doomscroll cookies on",
			"  /doomscroll muteothers on",
			"  /doomscroll cooldown 1500",
			"  /doomscroll maxpanel 64",
			"",
			"Public server, curated sites only:",
			"Halka acik sunucu, yalnizca secilmis siteler:",
			"  /doomscroll allow youtube.com",
			"  /doomscroll allow twitch.tv",
			"  /doomscroll cookies on",
			"  /doomscroll cooldown 1500",
			"",
			"Something is on a screen right now and has to stop:",
			"Su anda ekranda duran bir seyin durmasi gerekiyorsa:",
			"  /doomscroll emergency on        (then / sonra: /doomscroll audit 30)",
			"") + "\n";
}
